import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Ban Công Nghệ - Project Management",
  keywords: [
    "Ban Công Nghệ",
    "Project Management",
    "BCN",
    "Project",
    "Management",
    "Task Management",
    "Team Collaboration",
    "Productivity",
    "Project Tracking",
  ],
  authors: [
    {
      name: "Ban Công Nghệ",
    },
  ],
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="inner-main">
          {children}
        </main>
      </body>
    </html>
  );
}
