// import type { Metadata } from "next";
"use client";
import React, { useEffect } from "react";
import "./globals.css";

// export const metadata: Metadata = {
//   title: "Ban Công Nghệ - Project Management",
//   keywords: [
//     "Ban Công Nghệ",
//     "Project Management",
//     "BCN",
//     "Project",
//     "Management",
//     "Task Management",
//     "Team Collaboration",
//     "Productivity",
//     "Project Tracking",
//   ],
//   authors: [
//     {
//       name: "Ban Công Nghệ",
//     },
//   ],
//   description: "Generated by create next app",
// };

function saveOnlineTime() {
  const today = new Date();
  const key = `online_hours_${today.getFullYear()}_${today.getMonth() + 1}_${today.getDate()}`;
  let seconds = Number(localStorage.getItem(key) || 0);
  seconds += 1;
  localStorage.setItem(key, String(seconds));
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Đếm thời gian online toàn app
  useEffect(() => {
    const interval = setInterval(saveOnlineTime, 1000);
    return () => clearInterval(interval);
  }, []);

  return (
    <html lang="en">
      <body>
        <main className="inner-main">
          {children}
        </main>
      </body>
    </html>
  );
}
